///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Git
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GitRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("2db2e3cf-ae33-4f85-9911-4465830a702f")]
    public partial class GitRepository : RepoGenBaseFolder
    {
        static GitRepository instance = new GitRepository();

        /// <summary>
        /// Gets the singleton class instance representing the GitRepository element repository.
        /// </summary>
        [RepositoryFolder("2db2e3cf-ae33-4f85-9911-4465830a702f")]
        public static GitRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GitRepository() 
            : base("GitRepository", "/", null, 0, false, "2db2e3cf-ae33-4f85-9911-4465830a702f", ".\\RepositoryImages\\GitRepository2db2e3cf.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2db2e3cf-ae33-4f85-9911-4465830a702f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class GitRepositoryFolders
    {
    }
#pragma warning restore 0436
}